version = "3.10.7"
runner.dialect = scala3
align.preset = more
maxColumn = 100
# verticalMultiline.atDefnSite = true
newlines.usingParamListModifierPrefer = before
project.excludePaths = ["glob:**/generatedScriptSources.dest/**"]
